name: Setup Pact
description: Setup pact environment for running tests

inputs:
  version:
    description: "Target Pact version to install"
    required: false
    default: "5.2"

runs:
  using: composite
  steps:
    - name: Get pact binary
      shell: bash
      run: |
        mkdir bin
        cd bin
        wget https://github.com/kadena-io/pact-5/releases/download/${{ inputs.version }}/pact-${{ inputs.version }}-linux-x64.tar.gz
        tar -xzf "pact-${{ inputs.version }}-linux-x64.tar.gz"
        chmod +x pact
        cd ..

    - name: Install z3 (ubuntu-18.04)
      uses: pavpanchekha/setup-z3@0.2.0
      with:
        version: "4.8.10"
        architecture: "x64"
        distribution: "ubuntu-18.04"
